# Generated by Django 4.1.7 on 2023-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.TextField(default='lorem ipsum ksjhfkushcljknskj cnsckjslkfhj soilfjlsjcljs clksj clkj ls colisjlcj lisj clksj lk clnlsjcf ls clsj clc ls c lsljc ljldkjsfl  cslcjslkc', max_length=500),
        ),
    ]
