# Generated by Django 4.1.7 on 2023-05-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_admin_product_adminmail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
